// Generated by CoffeeScript 1.6.3
(function() {
  var Measures;

  Measures = require("../lib/measure");

  describe("General behaviour", function() {
    return it("should start and stop", function(cb) {
      var measures;
      measures = new Measures();
      measures.once("finished", function(samples) {
        return cb();
      });
      measures.start(0);
      return measures.stop();
    });
  });

}).call(this);
