// Generated by CoffeeScript 1.6.3
(function() {
  var libHttp, verkehr;

  libHttp = require("http");

  verkehr = require("../");

  describe("Monitoring Server", function() {
    var server;
    server = null;
    before(function(cb) {
      return server = new verkehr.Server(cb);
    });
    it("should start and stop", function(cb) {
      server.once("started", function() {
        server.once("stopped", cb);
        return server.stop();
      });
      return server.start();
    });
    return it("should receive samples", function(cb) {
      server.once("started", function() {
        var data, params, req;
        data = JSON.stringify({
          hello: "world"
        });
        params = {
          hostname: server.hostname,
          port: server.port,
          method: "POST",
          path: "/sample",
          headers: {
            "content-type": "application/json",
            "content-length": Buffer.byteLength(data)
          }
        };
        req = libHttp.request(params, function(res) {
          var _ref;
          if ((200 <= (_ref = res.statusCode) && _ref < 300)) {
            server.stop();
            return cb();
          } else {
            return cb(res.statusCode);
          }
        });
        return req.end(data);
      });
      return server.start();
    });
  });

}).call(this);
