// Generated by CoffeeScript 1.6.3
(function() {
  var Measures, libShould;

  libShould = require("should");

  Measures = require("../lib/measure");

  describe("Sample", function() {
    var measures, sample;
    sample = null;
    measures = null;
    before(function(cb) {
      measures = new Measures();
      measures.once("sampled", function(_sample) {
        sample = _sample;
        return cb();
      });
      return measures.start();
    });
    after(function(cb) {
      return measures.stop(cb);
    });
    it("should have a default property 'when' (Date)", function(cb) {
      sample.should.have.property("when");
      sample.when.should.be.an.instanceOf(Date);
      return cb();
    });
    it("should have a default property 'cpu' (Number)", function(cb) {
      sample.should.have.property("cpu");
      sample.cpu.should.be.an.Number;
      return cb();
    });
    return it("should have a default property 'memory' (Hash)", function(cb) {
      var mem;
      sample.should.have.property("memory");
      mem = sample.memory;
      mem.should.have.property("rss");
      mem.should.have.property("heapTotal");
      mem.should.have.property("heapUsed");
      return cb();
    });
  });

}).call(this);
