// Generated by CoffeeScript 1.6.3
var fetchData, handleData, handleError, parseValue;

parseValue = function(samples) {
  return "<pre>" + JSON.stringify(samples, null, 2) + "</pre>";
};

handleData = function(data) {
  var samples, uuid, _results;
  $("#no-connection").css("display", "none");
  _results = [];
  for (uuid in data) {
    samples = data[uuid];
    if ($("#" + uuid).length) {
      _results.push($("#" + uuid).children(".bla").html(parseValue(samples)));
    } else {
      _results.push($("#nodes").append("<div id=\"" + uuid + "\" class=\"node\">           <h3>" + uuid + "</h3>           <div class=\"bla\">" + (parseValue(samples)) + "</div>         </div>"));
    }
  }
  return _results;
};

handleError = function() {
  return $("#no-connection").css("display", "block");
};

fetchData = function() {
  return $.getJSON("/data", handleData).fail(handleError).always(function() {
    return setTimeout(fetchData, 1000);
  });
};

$(document).ready(function() {
  return fetchData();
});
