// Generated by CoffeeScript 1.6.3
(function() {
  var Measures, exports, libAsync, libEvents, libHttp, libUsage, libUuid,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  libAsync = require("async");

  libUsage = require("usage");

  libEvents = require("events");

  libHttp = require("http");

  libUuid = require("node-uuid");

  module.exports = exports = Measures = (function(_super) {
    __extends(Measures, _super);

    function Measures(cb) {
      var _this = this;
      this.measuring = {};
      this.names = [];
      this.sample = null;
      this.repeat = true;
      this.timeoutId = null;
      this.uuid = libUuid.v4();
      this.addMeasure("uuid", function(cb) {
        return cb(null, _this.uuid);
      });
      this.addMeasure("when", function(cb) {
        return cb(null, new Date());
      });
      this.addMeasure("cpu", function(cb) {
        return libUsage.lookup(process.pid, {
          keepHistory: false
        }, function(err, result) {
          if (err) {
            return cb(err);
          }
          return cb(null, result.cpu);
        });
      });
      this.addMeasure("memory", function(cb) {
        return cb(null, process.memoryUsage());
      });
      if (cb && typeof cb === "function") {
        cb();
      }
    }

    Measures.prototype.start = function(samplingRate, hostname, port) {
      var _this = this;
      this.samplingRate = samplingRate != null ? samplingRate : 5000;
      this.hostname = hostname != null ? hostname : "127.0.0.1";
      this.port = port != null ? port : 58241;
      return libAsync.doWhilst(this.takeSample.bind(this), (function() {
        return _this.repeat;
      }).bind(this), function(err) {
        if (err) {
          return _this.emit("error", err);
        }
        return _this.emit("finished");
      });
    };

    Measures.prototype.stop = function(cb) {
      this.repeat = false;
      clearTimeout(this.timeoutId);
      if (cb && typeof cb === "function") {
        return cb();
      }
    };

    Measures.prototype.addMeasure = function(name, samplingFunc) {
      if (!name || !samplingFunc) {
        return;
      }
      if (!(typeof name === "string") && !(name instanceof String)) {
        throw Error("name is not a string");
      }
      if (!(typeof samplingFunc === "function")) {
        throw Error("samplingFunc is not a function");
      }
      this.measuring[name] = samplingFunc;
      return this.names = Object.keys(this.measuring);
    };

    Measures.prototype.takeSample = function(cb) {
      var _this = this;
      this.sample = {};
      return libAsync.each(this.names, this.callSamplingFunc.bind(this), function(err) {
        var data, params, req;
        if (err) {
          return _this.emit("error", err);
        }
        data = JSON.stringify(_this.sample);
        params = {
          hostname: _this.hostname,
          port: _this.port,
          method: "POST",
          path: "/sample",
          headers: {
            "content-type": "application/json",
            "content-length": Buffer.byteLength(data)
          }
        };
        req = libHttp.request(params);
        req.on("error", function(err) {
          var msg;
          msg = "Could not connect to verkehrsmonitor using " + _this.hostname + ":" + _this.port;
          return _this.emit("warning", {
            msg: msg,
            sample: _this.sample
          });
        });
        req.end(data);
        _this.emit("sampled", _this.sample);
        return _this.timeoutId = setTimeout(cb, _this.samplingRate);
      });
    };

    Measures.prototype.callSamplingFunc = function(name, cb) {
      var samplingFunc,
        _this = this;
      samplingFunc = this.measuring[name];
      return samplingFunc(function(err, result) {
        if (err) {
          return cb(err);
        }
        _this.sample[name] = result;
        return cb();
      });
    };

    return Measures;

  })(libEvents.EventEmitter);

}).call(this);
