// Generated by CoffeeScript 1.6.3
(function() {
  var Server, exports, libEvents, libExpress, libHttp,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  libExpress = require("express");

  libHttp = require("http");

  libEvents = require("events");

  module.exports = exports = Server = (function(_super) {
    var STATE_STARTED, STATE_STARTING, STATE_STOPPED;

    __extends(Server, _super);

    Server.states = [STATE_STOPPED = 1, STATE_STARTING = 2, STATE_STARTED = 3];

    function Server(cb) {
      this.app = libExpress();
      this.app.use(libExpress.bodyParser());
      this.state = STATE_STOPPED;
      this.emit("initialized");
      this.emit("stopped");
      this.app.post("/sample", this.handleSample.bind(this));
      if (cb && typeof cb === "function") {
        cb();
      }
    }

    Server.prototype.start = function(port, hostname, backlog) {
      var _this = this;
      if (port == null) {
        port = 10000;
      }
      if (hostname == null) {
        hostname = void 0;
      }
      if (backlog == null) {
        backlog = void 0;
      }
      if (this.state === STATE_STOPPED) {
        this.httpServer = libHttp.createServer(this.app);
        this.state = STATE_STARTING;
        this.emit("starting");
        return this.httpServer.listen(port, hostname, backlog, function() {
          _this.state = STATE_STARTED;
          _this.emit("started");
          return _this.emit("info", "Monitoring server started on port " + port + ".");
        });
      }
    };

    Server.prototype.stop = function(cb) {
      if (this.state === STATE_STARTED) {
        this.httpServer.close();
        this.emit("info", "Monitoring server stopped.");
        this.state = STATE_STOPPED;
        this.emit("stopped");
      }
      if (cb && typeof cb === "function") {
        return cb();
      }
    };

    Server.prototype.handleSample = function(req, res) {
      var name, value, _ref, _results;
      _ref = req.body;
      _results = [];
      for (name in _ref) {
        value = _ref[name];
        console.log("" + name + ": " + value);
        this.emit("sample", req.body);
        _results.push(res.send(201));
      }
      return _results;
    };

    return Server;

  })(libEvents.EventEmitter);

}).call(this);
