// Generated by CoffeeScript 1.6.3
(function() {
  var checkInputAndStart, printHelp, verkehr;

  verkehr = require("./");

  printHelp = function() {
    return console.log("Usage: verkehrsmonitor [<port> [<hostname> [<backlog>]]]");
  };

  checkInputAndStart = function() {
    var arg, backlog, hostname, port, s, testPort;
    port = void 0;
    hostname = void 0;
    backlog = void 0;
    if (process.argv.length > 2) {
      arg = process.argv[2];
      if (arg === "help" || arg === "-h" || arg === "--help") {
        return printHelp();
      } else {
        testPort = parseInt(arg, 10);
        if ((1 <= testPort && testPort <= 65535)) {
          port = testPort;
        } else {
          return printHelp();
        }
      }
    }
    if (process.argv.length > 3) {
      hostname = process.argv[3];
    }
    if (process.argv.length > 4) {
      backlog = parseInt(process.argv[4], 10);
    }
    s = new verkehr.Server();
    s.start(port, hostname, backlog);
    return s.on("info", function(info) {
      return console.log(info);
    });
  };

  checkInputAndStart();

}).call(this);
